### ISSUE TITLE
Interactions Auto-resolve

### ISSUE THREAD

**Issue by Airbus-A330** [Liege72/LucaasBot#1]
You are currently resolving all interactions automatically with a type 5, which is interfering with other aspects of the bots including modmail slash commands and button presses.  Please merge the future PR (coming soon) fixing this issue.

Thanks!

**Comment by quinchs** [comment]
#2

**Comment by quinchs** [comment]
Fixed in [e996048](https://github.com/Liege72/LucaasBot/commit/e996048ec5627651535230c3ee686491a398c5b3)
